name: Sing-box node collection
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  collect_sing-box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Serenity and Sing-box
        run: |
          sudo curl -fsSL https://deb.sagernet.org/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
          sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y serenity sing-box

      - name: Run Node Collection using Serenity
        run: nohup serenity run -c .github/serenity.json &

      - name: Collect final.json
        run: sleep 10s; curl -fsSL http://127.0.0.1:8080/final | jq -Sc > final.json || echo "CURL FAILED!"

      - name: Merging with Templates
        run: bash .github/merge.sh

      - name: Testing Outputs using Sing-box
        run: for i in release/sing-box/*.json; do sing-box check -c ${i} && echo "${i} is OK!"; done

      - name: Update Rule-Set Binaries
        run: for i in direct.json block.json; do sing-box rule-set format -w ${i} && sing-box rule-set compile ${i}; done

      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Updated on: `date`" || echo "No changes to commit"
          git push
